Repository OutpostUniverse/OPHD, pull requests merged in 2021-11, with the labels that each got.

#1152 Fix null robot
  OPHD/States/MapViewState.cpp
  OPHD/States/MapViewState.h
  OPHD/States/MapViewStateEvent.cpp
  OPHD/States/MapViewStateIO.cpp
  OPHD/States/MapViewStateTurn.cpp
Labels: bug, intermediate

#1153 Refactor notifications
  OPHD/States/CrimeExecution.cpp
  OPHD/States/MapViewState.cpp
  OPHD/States/MapViewStateTurn.cpp
  OPHD/UI/NotificationArea.cpp
  OPHD/UI/NotificationArea.h
  OPHD/UI/NotificationWindow.cpp
Labels: task, User Interface

#1185 Fix incorrect structures in menu
  OPHD/States/MapViewState.cpp
  OPHD/States/MapViewStateUi.cpp
Labels: bug, easy

#1187 Refactor take me there
  OPHD/States/MapViewState.cpp
  OPHD/States/MapViewState.h
  OPHD/States/MapViewStateUi.cpp
Labels: task
